"""Pydantic v2 request/response schemas for the Coachin API."""

from app.schemas.chat import (
    ChatRequest,
    ChatResponse,
    ConversationRead,
    ConversationSummary,
    MessageRead,
    SafetyAssessment,
    SafetyEventRead,
    SafetyNotice,
)
from app.schemas.common import Message, Page
from app.schemas.exercise import ExerciseCreate, ExerciseRead, ExerciseSummary
from app.schemas.nutrition import (
    DailyNutritionSummary,
    MacroTotals,
    MealEstimateRequest,
    NutritionLogCreate,
    NutritionLogRead,
    NutritionLogUpdate,
)
from app.schemas.program import (
    PlannedExerciseCreate,
    PlannedExerciseRead,
    ProgramGenerateRequest,
    ProgramRead,
    ProgramSummary,
    ProgramUpdate,
    ProgramWorkoutCreate,
    ProgramWorkoutRead,
)
from app.schemas.progress import (
    BodyMetricCreate,
    BodyMetricRead,
    ProgressReportGenerateRequest,
    ProgressReportRead,
    ProgressReportSummary,
)
from app.schemas.user import (
    LoginRequest,
    Token,
    UserCreate,
    UserProfileCreate,
    UserProfileRead,
    UserProfileUpdate,
    UserRead,
    UserUpdate,
)
from app.schemas.voice import SpeechRequest, TranscriptionResponse, VoiceChatResponse
from app.schemas.workout import (
    ExerciseHistoryPoint,
    ExerciseSetCreate,
    ExerciseSetRead,
    OverloadRecommendation,
    WorkoutSessionCreate,
    WorkoutSessionRead,
    WorkoutSessionUpdate,
)

__all__ = [
    "BodyMetricCreate",
    "BodyMetricRead",
    "ChatRequest",
    "ChatResponse",
    "ConversationRead",
    "ConversationSummary",
    "DailyNutritionSummary",
    "ExerciseCreate",
    "ExerciseHistoryPoint",
    "ExerciseRead",
    "ExerciseSetCreate",
    "ExerciseSetRead",
    "ExerciseSummary",
    "LoginRequest",
    "MacroTotals",
    "MealEstimateRequest",
    "Message",
    "MessageRead",
    "NutritionLogCreate",
    "NutritionLogRead",
    "NutritionLogUpdate",
    "OverloadRecommendation",
    "Page",
    "PlannedExerciseCreate",
    "PlannedExerciseRead",
    "ProgramGenerateRequest",
    "ProgramRead",
    "ProgramSummary",
    "ProgramUpdate",
    "ProgramWorkoutCreate",
    "ProgramWorkoutRead",
    "ProgressReportGenerateRequest",
    "ProgressReportRead",
    "ProgressReportSummary",
    "SafetyAssessment",
    "SafetyEventRead",
    "SafetyNotice",
    "SpeechRequest",
    "Token",
    "TranscriptionResponse",
    "UserCreate",
    "UserProfileCreate",
    "UserProfileRead",
    "UserProfileUpdate",
    "UserRead",
    "UserUpdate",
    "VoiceChatResponse",
    "WorkoutSessionCreate",
    "WorkoutSessionRead",
    "WorkoutSessionUpdate",
]
